### ISSUE TITLE
Module 1 development : Field Papers

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#1]
[Modules](https://github.com/shawnmgoulet/teachosm-for-high-school#modules)

Module 1 is intended to step an educator through the process of creating, then guiding students through using field papers to use in a field exercise.

**Comment by TomM4** [comment]
Got it.

**Comment by shawnmgoulet** [comment]
working draft [here](https://docs.google.com/document/d/1afXAkSQz-AjkKltDRgAkYbszqh8JQ_Hsdlus-e8KqVQ/edit?usp=sharing).
