### ISSUE TITLE
Module 11 development : An Introduction to OSM Mapping Projects

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#10]
- Teachers will be guided how to give an overview of all OSM Mapping Projects.

- Students will "sign-up" for a project which they will complete the year contributing towards.

**Comment by geomantic** [comment]
Add: 

- Overview of the OSM tool suite (e.g. FieldPapers, iD & JOSM, Mapillary/OpenStreetCam, mobile apps)

- Grading and assessment using OSMCHA & Overpass-Turbo

- Micro-credentials and CE credits

- Service learning credit

**Comment by shawnmgoulet** [comment]
the above ideas can be worked in over time, but closing for now.
