### ISSUE TITLE
Module 12 development : Let's Organize a Mapathon

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#11]
- Teachers will be guided in best practices related to the organization of mapathons with the assistance of students.

- Students will promote the event, reach out to interested public members and will participate in the mapathon.

**Comment by geomantic** [comment]
This module can be created from materials I've developed for workshops for geography teachers.

**Comment by geomantic** [comment]
First draft here: https://docs.google.com/document/d/1HK7NE1sQrjC38NK-qay-GwnCqzQdyROxraHYRlhwiLY/edit?usp=sharing
