### ISSUE TITLE
Module 4 development : OSM Mapping Practice

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#13]
An interactive, hands-on, teacher-led workshop format where:

- Teachers will be guided on how to introduce and familiarize students with the **iD editor**.

- Teachers will be guided on covering **common iD editor shortcuts** with students.

- Teachers will be guided on using the **LearnOSM Beginner iD Editor Guide** with students.

- Teachers and studnts will conduct a live walk-through with students using the **iD Editor walkthrough**.

**Comment by geomantic** [comment]
I've got some materials to shape this module.

**Comment by shawnmgoulet** [comment]
@geomantic are you planning on developing this, or do you want to share your materials in [google drive](https://drive.google.com/drive/folders/0B3ZON0wGv7meRUZRXzRrZWRpSFU?usp=sharing) for someone else to develop?

**Comment by geomantic** [comment]
I can start on it today, since I have the most of the materials.

**Comment by shawnmgoulet** [comment]
Cool, no immediate rush, just was "up next" on my list to work on.

**Comment by geomantic** [comment]
Connect the toolset with the open mapping workflow.

**Comment by geomantic** [comment]
if no one objects, i'm altering the name slightly to, 'Editing OpenStreetMap'

**Comment by shawnmgoulet** [comment]
sounds good @geomantic !
