### ISSUE TITLE
Module 5 development : Mapping Population OSM Map Features

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#4]
- Population-related population and migration-related map features will be introduced by the teacher.

- Students will then map these features anywhere in the world.

- Specific map features and an example implementation approach will provided to the educator in this module.

**Comment by geomantic** [comment]
I could use additional ideas, but think I can bring some perspective to this module.

**Comment by shawnmgoulet** [comment]
I _think_ this is started **[here](https://docs.google.com/document/d/1WDLKVjC5J666AZM2VXkDYaTqCndeFZN9VyJRiU18-78/edit?usp=sharing)**...
