### ISSUE TITLE
Module 8 development : Mapping Agricultural and Rural Land Use OSM Map Features

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#7]
- Agricultural and rural land use map features will be introduced by the teacher.

- Students will then map these features anywhere in the world.

- Specific map features and an example implementation approach will provided to the educator in this module.

**Comment by geomantic** [comment]
Digitize worldwide agricultural regimes by creating jobs on the TeachOSM TM for use by students.

**Comment by geomantic** [comment]
Farm-to-market roads in rural areas

**Comment by shawnmgoulet** [comment]
Areas where access to safe/clean water is an issue is another options.  Examples include the Wakiso District, Uganda [1] (American Geographical Society Teacher Fellow Celeste Reynolds' 2017 APHG sections will be mapping buildings in their 2017 mapathon) & many more projects that The Water Project (+ others) are involved in [2].

[1] [Uganda: 1 Million Residents in Wakiso Use Unsafe Water, Says Cao - allAfrica.com](http://allafrica.com/stories/201706020369.html)
[2] [The Water Project Projects](https://thewaterproject.org/community/projects/)

**Comment by shawnmgoulet** [comment]
done [here](https://docs.google.com/document/d/1JLplucJzzXLSZxeVjFtofySirCdR6WZJ06SEbRqOS90/edit?usp=sharing)
