### ISSUE TITLE
Module 9 development : Mapping Industrialization and Economic Development OSM Map Features

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#8]
- Industrialization and economic development map features will be introduced by the teacher.

- Students will then map these features anywhere in the world.

- Specific map features and an example implementation approach will provided to the educator in this module.

**Comment by geomantic** [comment]
Digitizing worldwide industrial zones, e.g. Shenzhen, China, Gary, Indiana, Malaysia (steel), Korea (steel, shipping), maquiladora areas on the SW border, etc. Large harbors: Los Angeles, Sao Paolo, Rotterdam, Uganda.

**Comment by geomantic** [comment]
Add transport features: canals, rails, shipping facilities, etc. Farm-to-market roads

**Comment by shawnmgoulet** [comment]
For Uganda: Wakiso District is an area example of rapid urbanization; agriculture turning to trade and industry [1].  Celeste Reynolds' APHG class will be mapping buildings there for their 2 day mapathon June 12-13, 2017 connected to the District's issues with access to safe/clean water (APHG Unit 5).

[1] [Wakiso District Wikipedia](https://en.wikipedia.org/wiki/Wakiso_District)

**Comment by shawnmgoulet** [comment]
a transpo features exercise can be added over time, closing for now.
