### ISSUE TITLE
Module 10 development : Mapping Cities and Urban Land Use OSM Map Features

### ISSUE THREAD

**Issue by shawnmgoulet** [shawnmgoulet/teachosm-for-high-school#9]
- Cities and urban land use map features will be introduced by the teacher.

- Students will then map these features anywhere in the world.

- Specific map features and an example implementation approach will provided to the educator in this module.

**Comment by geomantic** [comment]
Use Overpass-Turbo to query the student's town: search for coffee shops, libraries, police/fire stations, and other services/features. If they're not there, digitize them in OpenStreetMap. 
Couple with American Factfinder to compare statistics in the town.
Search for parks and recreational facilities. If missing, add them to the map.

**Comment by shawnmgoulet** [comment]
completed [here](https://docs.google.com/document/d/1vWUGAxyiz3dKN0qEenpGIeRNxS4xlu2FuwG6cDv9x88/edit?usp=sharing)
